steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - '-c'
    - |
      gcloud compute ssh bastion-host \
      --zone us-central1-f \
      --command="hostname"

options:
  logging: CLOUD_LOGGING_ONLY