steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/demo-repo/private-gke-demo:$SHORT_SHA'
    - '.'

- name: 'gcr.io/cloud-builders/docker'
  args:
    - 'push'
    - 'us-central1-docker.pkg.dev/$PROJECT_ID/demo-repo/private-gke-demo:$SHORT_SHA'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
    - '-c'
    - |
      gcloud compute ssh dombalevarsha4@bastion-host \
      --zone us-central1-f \
      --command="
      sed -i 's|IMAGE_TAG|$SHORT_SHA|g' ~/k8s/flask-deployment.yaml &&
      kubectl apply -f ~/k8s
      "

options:
  logging: CLOUD_LOGGING_ONLY